### ISSUE TITLE
Change to Bungeecord

### ISSUE THREAD

**Issue by ItsKev** [ItsKev/server-discovery#3]
Changing to Bungeecord should make the plugin available to a broader audience. Waterfall should still work without changing anything. This has to be tested first though.

**Comment by siddharth1704** [comment]
how is this done can you tell, i want to start it with but have no idea

**Comment by ItsKev** [comment]
@siddharth1704 Sorry got no notification for it. Just replace the Waterfall dependency with the Bungeecord one and test if everything still works as expected.

**Comment by ItsKev** [comment]
Can't be fixed that easily. Bungecoord uses a Map that gets modified concurrently by the proxy. Therefore Exception could be thrown in the worst scenario.

I'll close the issue for now and leave the implementation on Waterfall instead.
